package Bd;
// Generated 30 mars 2019 16:35:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;

/**
 * Choisir generated by hbm2java
 */
public class Choisir  implements java.io.Serializable {


     private ChoisirId id;
     private Client client;
     private Objectif objectif;
     private Date datedemande;

    public Choisir() {
    }

	
    public Choisir(ChoisirId id, Client client, Objectif objectif) {
        this.id = id;
        this.client = client;
        this.objectif = objectif;
    }
    public Choisir(ChoisirId id, Client client, Objectif objectif, Date datedemande) {
       this.id = id;
       this.client = client;
       this.objectif = objectif;
       this.datedemande = datedemande;
    }
   
    public ChoisirId getId() {
        return this.id;
    }
    
    public void setId(ChoisirId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Objectif getObjectif() {
        return this.objectif;
    }
    
    public void setObjectif(Objectif objectif) {
        this.objectif = objectif;
    }
    public Date getDatedemande() {
        return this.datedemande;
    }
    
    public void setDatedemande(Date datedemande) {
        this.datedemande = datedemande;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 17 * hash + Objects.hashCode(this.id);
        hash = 17 * hash + Objects.hashCode(this.datedemande);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Choisir other = (Choisir) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.datedemande, other.datedemande)) {
            return false;
        }
        return true;
    }

    


}


