package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Choisir generated by hbm2java
 */
public class Choisir  implements java.io.Serializable {


     private ChoisirId id;
     private Client client;
     private Objectif objectif;
     private Date datedemande;

    public Choisir() {
    }

	
    public Choisir(ChoisirId id, Client client, Objectif objectif) {
        this.id = id;
        this.client = client;
        this.objectif = objectif;
    }
    public Choisir(ChoisirId id, Client client, Objectif objectif, Date datedemande) {
       this.id = id;
       this.client = client;
       this.objectif = objectif;
       this.datedemande = datedemande;
    }
   
    public ChoisirId getId() {
        return this.id;
    }
    
    public void setId(ChoisirId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Objectif getObjectif() {
        return this.objectif;
    }
    
    public void setObjectif(Objectif objectif) {
        this.objectif = objectif;
    }
    public Date getDatedemande() {
        return this.datedemande;
    }
    
    public void setDatedemande(Date datedemande) {
        this.datedemande = datedemande;
    }




}


