package Bd;
// Generated 30 mars 2019 16:35:04 by Hibernate Tools 4.3.1



/**
 * ChoisirId generated by hbm2java
 */
public class ChoisirId  implements java.io.Serializable {


     private int idobj;
     private int idc;

    public ChoisirId() {
    }

    public ChoisirId(int idobj, int idc) {
       this.idobj = idobj;
       this.idc = idc;
    }
   
    public int getIdobj() {
        return this.idobj;
    }
    
    public void setIdobj(int idobj) {
        this.idobj = idobj;
    }
    public int getIdc() {
        return this.idc;
    }
    
    public void setIdc(int idc) {
        this.idc = idc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChoisirId) ) return false;
		 ChoisirId castOther = ( ChoisirId ) other; 
         
		 return (this.getIdobj()==castOther.getIdobj())
 && (this.getIdc()==castOther.getIdc());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdobj();
         result = 37 * result + this.getIdc();
         return result;
   }   


}


