package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idc;
     private String nomc;
     private String prenomc;
     private String telc;
     private String emailc;
     private String adressec;
     private String sexec;
     private String photoc;
     private String etatc;
     private Set programmepersos = new HashSet(0);
     private Set coaches = new HashSet(0);
     private Set choisirs = new HashSet(0);

    public Client() {
    }

    public Client(String nomc, String prenomc, String telc, String emailc, String adressec, String sexec, String photoc, String etatc, Set programmepersos, Set coaches, Set choisirs) {
       this.nomc = nomc;
       this.prenomc = prenomc;
       this.telc = telc;
       this.emailc = emailc;
       this.adressec = adressec;
       this.sexec = sexec;
       this.photoc = photoc;
       this.etatc = etatc;
       this.programmepersos = programmepersos;
       this.coaches = coaches;
       this.choisirs = choisirs;
    }
   
    public Integer getIdc() {
        return this.idc;
    }
    
    public void setIdc(Integer idc) {
        this.idc = idc;
    }
    public String getNomc() {
        return this.nomc;
    }
    
    public void setNomc(String nomc) {
        this.nomc = nomc;
    }
    public String getPrenomc() {
        return this.prenomc;
    }
    
    public void setPrenomc(String prenomc) {
        this.prenomc = prenomc;
    }
    public String getTelc() {
        return this.telc;
    }
    
    public void setTelc(String telc) {
        this.telc = telc;
    }
    public String getEmailc() {
        return this.emailc;
    }
    
    public void setEmailc(String emailc) {
        this.emailc = emailc;
    }
    public String getAdressec() {
        return this.adressec;
    }
    
    public void setAdressec(String adressec) {
        this.adressec = adressec;
    }
    public String getSexec() {
        return this.sexec;
    }
    
    public void setSexec(String sexec) {
        this.sexec = sexec;
    }
    public String getPhotoc() {
        return this.photoc;
    }
    
    public void setPhotoc(String photoc) {
        this.photoc = photoc;
    }
    public String getEtatc() {
        return this.etatc;
    }
    
    public void setEtatc(String etatc) {
        this.etatc = etatc;
    }
    public Set getProgrammepersos() {
        return this.programmepersos;
    }
    
    public void setProgrammepersos(Set programmepersos) {
        this.programmepersos = programmepersos;
    }
    public Set getCoaches() {
        return this.coaches;
    }
    
    public void setCoaches(Set coaches) {
        this.coaches = coaches;
    }
    public Set getChoisirs() {
        return this.choisirs;
    }
    
    public void setChoisirs(Set choisirs) {
        this.choisirs = choisirs;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + Objects.hashCode(this.idc);
        hash = 29 * hash + Objects.hashCode(this.nomc);
        hash = 29 * hash + Objects.hashCode(this.prenomc);
        hash = 29 * hash + Objects.hashCode(this.telc);
        hash = 29 * hash + Objects.hashCode(this.emailc);
        hash = 29 * hash + Objects.hashCode(this.adressec);
        hash = 29 * hash + Objects.hashCode(this.sexec);
        hash = 29 * hash + Objects.hashCode(this.photoc);
        hash = 29 * hash + Objects.hashCode(this.etatc);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Client other = (Client) obj;
        if (!Objects.equals(this.nomc, other.nomc)) {
            return false;
        }
        if (!Objects.equals(this.prenomc, other.prenomc)) {
            return false;
        }
        if (!Objects.equals(this.telc, other.telc)) {
            return false;
        }
        if (!Objects.equals(this.emailc, other.emailc)) {
            return false;
        }
        if (!Objects.equals(this.adressec, other.adressec)) {
            return false;
        }
        if (!Objects.equals(this.sexec, other.sexec)) {
            return false;
        }
        if (!Objects.equals(this.photoc, other.photoc)) {
            return false;
        }
        if (!Objects.equals(this.etatc, other.etatc)) {
            return false;
        }
        if (!Objects.equals(this.idc, other.idc)) {
            return false;
        }
        return true;
    }

//    public static trouverClient(integer idC){
//        if (idC.equalsto)
//    }



}


