package Bd;
// Generated 30 mars 2019 16:35:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Coach generated by hbm2java
 */
public class Coach  implements java.io.Serializable {


     private Integer idco;
     private String nomco;
     private String prenomco;
     private String telco;
     private String emailco;
     private Set clients = new HashSet(0);

    public Coach() {
    }

    public Coach(String nomco, String prenomco, String telco, String emailco, Set clients) {
       this.nomco = nomco;
       this.prenomco = prenomco;
       this.telco = telco;
       this.emailco = emailco;
       this.clients = clients;
    }
   
    public Integer getIdco() {
        return this.idco;
    }
    
    public void setIdco(Integer idco) {
        this.idco = idco;
    }
    public String getNomco() {
        return this.nomco;
    }
    
    public void setNomco(String nomco) {
        this.nomco = nomco;
    }
    public String getPrenomco() {
        return this.prenomco;
    }
    
    public void setPrenomco(String prenomco) {
        this.prenomco = prenomco;
    }
    public String getTelco() {
        return this.telco;
    }
    
    public void setTelco(String telco) {
        this.telco = telco;
    }
    public String getEmailco() {
        return this.emailco;
    }
    
    public void setEmailco(String emailco) {
        this.emailco = emailco;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 83 * hash + Objects.hashCode(this.idco);
        hash = 83 * hash + Objects.hashCode(this.nomco);
        hash = 83 * hash + Objects.hashCode(this.prenomco);
        hash = 83 * hash + Objects.hashCode(this.telco);
        hash = 83 * hash + Objects.hashCode(this.emailco);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coach other = (Coach) obj;
        if (!Objects.equals(this.nomco, other.nomco)) {
            return false;
        }
        if (!Objects.equals(this.prenomco, other.prenomco)) {
            return false;
        }
        if (!Objects.equals(this.telco, other.telco)) {
            return false;
        }
        if (!Objects.equals(this.emailco, other.emailco)) {
            return false;
        }
        if (!Objects.equals(this.idco, other.idco)) {
            return false;
        }
        return true;
    }

    


}


