package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Exerciseperso generated by hbm2java
 */
public class Exerciseperso  implements java.io.Serializable {


     private Integer idexe;
     private Seanceperso seanceperso;
     private String libexe;
     private String descripexe;
     private String dureeexe;
     private String nbrepet;
     private String photoexe;
     private String videoexe;
     private Integer ordreexe;
     private String performance;
     private String dureereal;
     private Integer nbrepetreal;

    public Exerciseperso() {
    }

	
    public Exerciseperso(Seanceperso seanceperso) {
        this.seanceperso = seanceperso;
    }
    public Exerciseperso(Seanceperso seanceperso, String libexe, String descripexe, String dureeexe, String nbrepet, String photoexe, String videoexe, Integer ordreexe, String performance, String dureereal, Integer nbrepetreal) {
       this.seanceperso = seanceperso;
       this.libexe = libexe;
       this.descripexe = descripexe;
       this.dureeexe = dureeexe;
       this.nbrepet = nbrepet;
       this.photoexe = photoexe;
       this.videoexe = videoexe;
       this.ordreexe = ordreexe;
       this.performance = performance;
       this.dureereal = dureereal;
       this.nbrepetreal = nbrepetreal;
    }
   
    public Integer getIdexe() {
        return this.idexe;
    }
    
    public void setIdexe(Integer idexe) {
        this.idexe = idexe;
    }
    public Seanceperso getSeanceperso() {
        return this.seanceperso;
    }
    
    public void setSeanceperso(Seanceperso seanceperso) {
        this.seanceperso = seanceperso;
    }
    public String getLibexe() {
        return this.libexe;
    }
    
    public void setLibexe(String libexe) {
        this.libexe = libexe;
    }
    public String getDescripexe() {
        return this.descripexe;
    }
    
    public void setDescripexe(String descripexe) {
        this.descripexe = descripexe;
    }
    public String getDureeexe() {
        return this.dureeexe;
    }
    
    public void setDureeexe(String dureeexe) {
        this.dureeexe = dureeexe;
    }
    public String getNbrepet() {
        return this.nbrepet;
    }
    
    public void setNbrepet(String nbrepet) {
        this.nbrepet = nbrepet;
    }
    public String getPhotoexe() {
        return this.photoexe;
    }
    
    public void setPhotoexe(String photoexe) {
        this.photoexe = photoexe;
    }
    public String getVideoexe() {
        return this.videoexe;
    }
    
    public void setVideoexe(String videoexe) {
        this.videoexe = videoexe;
    }
    public Integer getOrdreexe() {
        return this.ordreexe;
    }
    
    public void setOrdreexe(Integer ordreexe) {
        this.ordreexe = ordreexe;
    }
    public String getPerformance() {
        return this.performance;
    }
    
    public void setPerformance(String performance) {
        this.performance = performance;
    }
    public String getDureereal() {
        return this.dureereal;
    }
    
    public void setDureereal(String dureereal) {
        this.dureereal = dureereal;
    }
    public Integer getNbrepetreal() {
        return this.nbrepetreal;
    }
    
    public void setNbrepetreal(Integer nbrepetreal) {
        this.nbrepetreal = nbrepetreal;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 73 * hash + Objects.hashCode(this.idexe);
        hash = 73 * hash + Objects.hashCode(this.libexe);
        hash = 73 * hash + Objects.hashCode(this.descripexe);
        hash = 73 * hash + Objects.hashCode(this.dureeexe);
        hash = 73 * hash + Objects.hashCode(this.nbrepet);
        hash = 73 * hash + Objects.hashCode(this.photoexe);
        hash = 73 * hash + Objects.hashCode(this.videoexe);
        hash = 73 * hash + Objects.hashCode(this.ordreexe);
        hash = 73 * hash + Objects.hashCode(this.performance);
        hash = 73 * hash + Objects.hashCode(this.dureereal);
        hash = 73 * hash + Objects.hashCode(this.nbrepetreal);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Exerciseperso other = (Exerciseperso) obj;
        if (!Objects.equals(this.libexe, other.libexe)) {
            return false;
        }
        if (!Objects.equals(this.descripexe, other.descripexe)) {
            return false;
        }
        if (!Objects.equals(this.photoexe, other.photoexe)) {
            return false;
        }
        if (!Objects.equals(this.videoexe, other.videoexe)) {
            return false;
        }
        if (!Objects.equals(this.performance, other.performance)) {
            return false;
        }
        if (!Objects.equals(this.idexe, other.idexe)) {
            return false;
        }
        if (!Objects.equals(this.dureeexe, other.dureeexe)) {
            return false;
        }
        if (!Objects.equals(this.nbrepet, other.nbrepet)) {
            return false;
        }
        if (!Objects.equals(this.ordreexe, other.ordreexe)) {
            return false;
        }
        if (!Objects.equals(this.dureereal, other.dureereal)) {
            return false;
        }
        if (!Objects.equals(this.nbrepetreal, other.nbrepetreal)) {
            return false;
        }
        return true;
    }




}


