package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exercisestandard generated by hbm2java
 */
public class Exercisestandard  implements java.io.Serializable {


     private Integer idexes;
     private String libexes;
     private String descripexes;
     private Integer dureeexes;
     private Integer nbrepets;
     private String photoexe;
     private String videoexe;
     private Set seancestandards = new HashSet(0);

    public Exercisestandard() {
    }

    public Exercisestandard(String libexes, String descripexes, Integer dureeexes, Integer nbrepets, String photoexe, String videoexe, Set seancestandards) {
       this.libexes = libexes;
       this.descripexes = descripexes;
       this.dureeexes = dureeexes;
       this.nbrepets = nbrepets;
       this.photoexe = photoexe;
       this.videoexe = videoexe;
       this.seancestandards = seancestandards;
    }
   
    public Integer getIdexes() {
        return this.idexes;
    }
    
    public void setIdexes(Integer idexes) {
        this.idexes = idexes;
    }
    public String getLibexes() {
        return this.libexes;
    }
    
    public void setLibexes(String libexes) {
        this.libexes = libexes;
    }
    public String getDescripexes() {
        return this.descripexes;
    }
    
    public void setDescripexes(String descripexes) {
        this.descripexes = descripexes;
    }
    public Integer getDureeexes() {
        return this.dureeexes;
    }
    
    public void setDureeexes(Integer dureeexes) {
        this.dureeexes = dureeexes;
    }
    public Integer getNbrepets() {
        return this.nbrepets;
    }
    
    public void setNbrepets(Integer nbrepets) {
        this.nbrepets = nbrepets;
    }
    public String getPhotoexe() {
        return this.photoexe;
    }
    
    public void setPhotoexe(String photoexe) {
        this.photoexe = photoexe;
    }
    public String getVideoexe() {
        return this.videoexe;
    }
    
    public void setVideoexe(String videoexe) {
        this.videoexe = videoexe;
    }
    public Set getSeancestandards() {
        return this.seancestandards;
    }
    
    public void setSeancestandards(Set seancestandards) {
        this.seancestandards = seancestandards;
    }




}


