package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1



/**
 * Exerciseperso generated by hbm2java
 */
public class Exerciseperso  implements java.io.Serializable {


     private Integer idexe;
     private Seanceperso seanceperso;
     private String libexe;
     private String descripexe;
     private Integer dureeexe;
     private Integer nbrepet;
     private String photoexe;
     private String videoexe;
     private Integer ordreexe;
     private String performance;
     private Integer dureereal;
     private Integer nbrepetreal;

    public Exerciseperso() {
    }

	
    public Exerciseperso(Seanceperso seanceperso) {
        this.seanceperso = seanceperso;
    }
    public Exerciseperso(Seanceperso seanceperso, String libexe, String descripexe, Integer dureeexe, Integer nbrepet, String photoexe, String videoexe, Integer ordreexe, String performance, Integer dureereal, Integer nbrepetreal) {
       this.seanceperso = seanceperso;
       this.libexe = libexe;
       this.descripexe = descripexe;
       this.dureeexe = dureeexe;
       this.nbrepet = nbrepet;
       this.photoexe = photoexe;
       this.videoexe = videoexe;
       this.ordreexe = ordreexe;
       this.performance = performance;
       this.dureereal = dureereal;
       this.nbrepetreal = nbrepetreal;
    }
   
    public Integer getIdexe() {
        return this.idexe;
    }
    
    public void setIdexe(Integer idexe) {
        this.idexe = idexe;
    }
    public Seanceperso getSeanceperso() {
        return this.seanceperso;
    }
    
    public void setSeanceperso(Seanceperso seanceperso) {
        this.seanceperso = seanceperso;
    }
    public String getLibexe() {
        return this.libexe;
    }
    
    public void setLibexe(String libexe) {
        this.libexe = libexe;
    }
    public String getDescripexe() {
        return this.descripexe;
    }
    
    public void setDescripexe(String descripexe) {
        this.descripexe = descripexe;
    }
    public Integer getDureeexe() {
        return this.dureeexe;
    }
    
    public void setDureeexe(Integer dureeexe) {
        this.dureeexe = dureeexe;
    }
    public Integer getNbrepet() {
        return this.nbrepet;
    }
    
    public void setNbrepet(Integer nbrepet) {
        this.nbrepet = nbrepet;
    }
    public String getPhotoexe() {
        return this.photoexe;
    }
    
    public void setPhotoexe(String photoexe) {
        this.photoexe = photoexe;
    }
    public String getVideoexe() {
        return this.videoexe;
    }
    
    public void setVideoexe(String videoexe) {
        this.videoexe = videoexe;
    }
    public Integer getOrdreexe() {
        return this.ordreexe;
    }
    
    public void setOrdreexe(Integer ordreexe) {
        this.ordreexe = ordreexe;
    }
    public String getPerformance() {
        return this.performance;
    }
    
    public void setPerformance(String performance) {
        this.performance = performance;
    }
    public Integer getDureereal() {
        return this.dureereal;
    }
    
    public void setDureereal(Integer dureereal) {
        this.dureereal = dureereal;
    }
    public Integer getNbrepetreal() {
        return this.nbrepetreal;
    }
    
    public void setNbrepetreal(Integer nbrepetreal) {
        this.nbrepetreal = nbrepetreal;
    }




}


