package Bd;
// Generated 30 mars 2019 16:35:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Exercisestandard generated by hbm2java
 */
public class Exercisestandard  implements java.io.Serializable {


     private Integer idexes;
     private String libexes;
     private String descripexes;
     private String dureeexes;
     private String nbrepets;
     private String photoexe;
     private String videoexe;
     private String materiel;
     private Set possederseas = new HashSet(0);

    public Exercisestandard() {
    }

    public Exercisestandard(String libexes, String descripexes, String dureeexes, String nbrepets, String photoexe, String videoexe, String materiel, Set possederseas) {
       this.libexes = libexes;
       this.descripexes = descripexes;
       this.dureeexes = dureeexes;
       this.nbrepets = nbrepets;
       this.photoexe = photoexe;
       this.videoexe = videoexe;
       this.materiel = materiel;
       this.possederseas = possederseas;
    }
   
    public Integer getIdexes() {
        return this.idexes;
    }
    
    public void setIdexes(Integer idexes) {
        this.idexes = idexes;
    }
    public String getLibexes() {
        return this.libexes;
    }
    
    public void setLibexes(String libexes) {
        this.libexes = libexes;
    }
    public String getDescripexes() {
        return this.descripexes;
    }
    
    public void setDescripexes(String descripexes) {
        this.descripexes = descripexes;
    }
    public String getDureeexes() {
        return this.dureeexes;
    }
    
    public void setDureeexes(String dureeexes) {
        this.dureeexes = dureeexes;
    }
    public String getNbrepets() {
        return this.nbrepets;
    }
    
    public void setNbrepets(String nbrepets) {
        this.nbrepets = nbrepets;
    }
    public String getPhotoexe() {
        return this.photoexe;
    }
    
    public void setPhotoexe(String photoexe) {
        this.photoexe = photoexe;
    }
    public String getVideoexe() {
        return this.videoexe;
    }
    
    public void setVideoexe(String videoexe) {
        this.videoexe = videoexe;
    }
    public String getMateriel() {
        return this.materiel;
    }
    
    public void setMateriel(String materiel) {
        this.materiel = materiel;
    }
    public Set getPossederseas() {
        return this.possederseas;
    }
    
    public void setPossederseas(Set possederseas) {
        this.possederseas = possederseas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 73 * hash + Objects.hashCode(this.idexes);
        hash = 73 * hash + Objects.hashCode(this.libexes);
        hash = 73 * hash + Objects.hashCode(this.descripexes);
        hash = 73 * hash + Objects.hashCode(this.dureeexes);
        hash = 73 * hash + Objects.hashCode(this.nbrepets);
        hash = 73 * hash + Objects.hashCode(this.photoexe);
        hash = 73 * hash + Objects.hashCode(this.videoexe);
        hash = 73 * hash + Objects.hashCode(this.materiel);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Exercisestandard other = (Exercisestandard) obj;
        if (!Objects.equals(this.libexes, other.libexes)) {
            return false;
        }
        if (!Objects.equals(this.descripexes, other.descripexes)) {
            return false;
        }
        if (!Objects.equals(this.dureeexes, other.dureeexes)) {
            return false;
        }
        if (!Objects.equals(this.nbrepets, other.nbrepets)) {
            return false;
        }
        if (!Objects.equals(this.photoexe, other.photoexe)) {
            return false;
        }
        if (!Objects.equals(this.videoexe, other.videoexe)) {
            return false;
        }
        if (!Objects.equals(this.materiel, other.materiel)) {
            return false;
        }
        if (!Objects.equals(this.idexes, other.idexes)) {
            return false;
        }
        return true;
    }




}


