package Bd;
// Generated 30 mars 2019 16:35:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Objectif generated by hbm2java
 */
public class Objectif  implements java.io.Serializable {


     private Integer idobj;
     private String libobj;
     private String descripobj;
     private Set choisirs = new HashSet(0);
     private Set programmepersos = new HashSet(0);
     private Set programmestandards = new HashSet(0);

    public Objectif() {
    }

    public Objectif(String libobj, String descripobj, Set choisirs, Set programmepersos, Set programmestandards) {
       this.libobj = libobj;
       this.descripobj = descripobj;
       this.choisirs = choisirs;
       this.programmepersos = programmepersos;
       this.programmestandards = programmestandards;
    }
   
    public Integer getIdobj() {
        return this.idobj;
    }
    
    public void setIdobj(Integer idobj) {
        this.idobj = idobj;
    }
    public String getLibobj() {
        return this.libobj;
    }
    
    public void setLibobj(String libobj) {
        this.libobj = libobj;
    }
    public String getDescripobj() {
        return this.descripobj;
    }
    
    public void setDescripobj(String descripobj) {
        this.descripobj = descripobj;
    }
    public Set getChoisirs() {
        return this.choisirs;
    }
    
    public void setChoisirs(Set choisirs) {
        this.choisirs = choisirs;
    }
    public Set getProgrammepersos() {
        return this.programmepersos;
    }
    
    public void setProgrammepersos(Set programmepersos) {
        this.programmepersos = programmepersos;
    }
    public Set getProgrammestandards() {
        return this.programmestandards;
    }
    
    public void setProgrammestandards(Set programmestandards) {
        this.programmestandards = programmestandards;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + Objects.hashCode(this.idobj);
        hash = 71 * hash + Objects.hashCode(this.libobj);
        hash = 71 * hash + Objects.hashCode(this.descripobj);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Objectif other = (Objectif) obj;
        if (!Objects.equals(this.libobj, other.libobj)) {
            return false;
        }
        if (!Objects.equals(this.descripobj, other.descripobj)) {
            return false;
        }
        if (!Objects.equals(this.idobj, other.idobj)) {
            return false;
        }
        return true;
    }




}


