package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Objectif generated by hbm2java
 */
public class Objectif  implements java.io.Serializable {


     private Integer idobj;
     private String libobj;
     private String descripobj;
     private Set choisirs = new HashSet(0);
     private Set programmepersos = new HashSet(0);
     private Set programmestandards = new HashSet(0);

    public Objectif() {
    }

    public Objectif(String libobj, String descripobj, Set choisirs, Set programmepersos, Set programmestandards) {
       this.libobj = libobj;
       this.descripobj = descripobj;
       this.choisirs = choisirs;
       this.programmepersos = programmepersos;
       this.programmestandards = programmestandards;
    }
   
    public Integer getIdobj() {
        return this.idobj;
    }
    
    public void setIdobj(Integer idobj) {
        this.idobj = idobj;
    }
    public String getLibobj() {
        return this.libobj;
    }
    
    public void setLibobj(String libobj) {
        this.libobj = libobj;
    }
    public String getDescripobj() {
        return this.descripobj;
    }
    
    public void setDescripobj(String descripobj) {
        this.descripobj = descripobj;
    }
    public Set getChoisirs() {
        return this.choisirs;
    }
    
    public void setChoisirs(Set choisirs) {
        this.choisirs = choisirs;
    }
    public Set getProgrammepersos() {
        return this.programmepersos;
    }
    
    public void setProgrammepersos(Set programmepersos) {
        this.programmepersos = programmepersos;
    }
    public Set getProgrammestandards() {
        return this.programmestandards;
    }
    
    public void setProgrammestandards(Set programmestandards) {
        this.programmestandards = programmestandards;
    }




}


