package Bd;
// Generated 30 mars 2019 16:35:04 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Possederps generated by hbm2java
 */
public class Possederps  implements java.io.Serializable {


     private PossederpsId id;
     private Programmestandard programmestandard;
     private Seancestandard seancestandard;

     private int semainesea;


    public Possederps() {
    }

    public Possederps(PossederpsId id, Programmestandard programmestandard, Seancestandard seancestandard, int semainesea) {
       this.id = id;
       this.programmestandard = programmestandard;
       this.seancestandard = seancestandard;
       this.semainesea = semainesea;

    }

    public PossederpsId getId() {
        return this.id;
    }

    public void setId(PossederpsId id) {
        this.id = id;
    }
    public Programmestandard getProgrammestandard() {
        return this.programmestandard;
    }

    public void setProgrammestandard(Programmestandard programmestandard) {
        this.programmestandard = programmestandard;
    }
    public Seancestandard getSeancestandard() {
        return this.seancestandard;
    }

    public void setSeancestandard(Seancestandard seancestandard) {
        this.seancestandard = seancestandard;
    }
    public int getSemainesea() {
        return this.semainesea;
    }

    public void setSemainesea(int semainesea) {
        this.semainesea = semainesea;
    }

    public void setSemainesea(Integer semainesea) {
        this.semainesea = semainesea;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 83 * hash + Objects.hashCode(this.id);
        hash = 83 * hash + this.semainesea;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Possederps other = (Possederps) obj;
        if (this.semainesea != other.semainesea) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }




}


