package Bd;
// Generated 30 mars 2019 16:35:04 by Hibernate Tools 4.3.1



/**
 * PossederpsId generated by hbm2java
 */
public class PossederpsId  implements java.io.Serializable {


     private int idps;
     private int idseas;
     private int ordredefaut;

    public PossederpsId() {
    }

    public PossederpsId(int idps, int idseas, int ordredefaut) {
       this.idps = idps;
       this.idseas = idseas;
       this.ordredefaut = ordredefaut;
    }
   
    public int getIdps() {
        return this.idps;
    }
    
    public void setIdps(int idps) {
        this.idps = idps;
    }
    public int getIdseas() {
        return this.idseas;
    }
    
    public void setIdseas(int idseas) {
        this.idseas = idseas;
    }
    public int getOrdredefaut() {
        return this.ordredefaut;
    }
    
    public void setOrdredefaut(int ordredefaut) {
        this.ordredefaut = ordredefaut;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PossederpsId) ) return false;
		 PossederpsId castOther = ( PossederpsId ) other; 
         
		 return (this.getIdps()==castOther.getIdps())
 && (this.getIdseas()==castOther.getIdseas())
 && (this.getOrdredefaut()==castOther.getOrdredefaut());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdps();
         result = 37 * result + this.getIdseas();
         result = 37 * result + this.getOrdredefaut();
         return result;
   }   


}


