package Bd;
// Generated 30 mars 2019 16:35:04 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Possedersea generated by hbm2java
 */
public class Possedersea  implements java.io.Serializable {


     private PossederseaId id;
     private Exercisestandard exercisestandard;
     private Seancestandard seancestandard;

    public Possedersea() {
    }

    public Possedersea(PossederseaId id, Exercisestandard exercisestandard, Seancestandard seancestandard) {
       this.id = id;
       this.exercisestandard = exercisestandard;
       this.seancestandard = seancestandard;
    }
   
    public PossederseaId getId() {
        return this.id;
    }
    
    public void setId(PossederseaId id) {
        this.id = id;
    }
    public Exercisestandard getExercisestandard() {
        return this.exercisestandard;
    }
    
    public void setExercisestandard(Exercisestandard exercisestandard) {
        this.exercisestandard = exercisestandard;
    }
    public Seancestandard getSeancestandard() {
        return this.seancestandard;
    }
    
    public void setSeancestandard(Seancestandard seancestandard) {
        this.seancestandard = seancestandard;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Possedersea other = (Possedersea) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }




}


