package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1



/**
 * PossederpsId generated by hbm2java
 */
public class PossederpsId  implements java.io.Serializable {


     private int idps;
     private int idseas;
     private int ordredefaut;

    public PossederpsId() {
    }

    public PossederpsId(int idps, int idseas, int ordredefaut) {
       this.idps = idps;
       this.idseas = idseas;
       this.ordredefaut=ordredefaut;
    }
   
    public int getIdps() {
        return this.idps;
    }
    
    public void setIdps(int idps) {
        this.idps = idps;
    }
    public int getIdseas() {
        return this.idseas;
    }
    
    public void setIdseas(int idseas) {
        this.idseas = idseas;
    }

    public int getOrdredefaut() {
        return ordredefaut;
    }

    public void setOrdredefaut(int ordredefaut) {
        this.ordredefaut = ordredefaut;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 79 * hash + this.idps;
        hash = 79 * hash + this.idseas;
        hash = 79 * hash + this.ordredefaut;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PossederpsId other = (PossederpsId) obj;
        if (this.idps != other.idps) {
            return false;
        }
        if (this.idseas != other.idseas) {
            return false;
        }
        if (this.ordredefaut != other.ordredefaut) {
            return false;
        }
        return true;
    }


   


}


