package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1



/**
 * PossederpsId generated by hbm2java
 */
public class PossederpsId  implements java.io.Serializable {


     private int idps;
     private int idseas;

    public PossederpsId() {
    }

    public PossederpsId(int idps, int idseas) {
       this.idps = idps;
       this.idseas = idseas;
    }
   
    public int getIdps() {
        return this.idps;
    }
    
    public void setIdps(int idps) {
        this.idps = idps;
    }
    public int getIdseas() {
        return this.idseas;
    }
    
    public void setIdseas(int idseas) {
        this.idseas = idseas;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PossederpsId) ) return false;
		 PossederpsId castOther = ( PossederpsId ) other; 
         
		 return (this.getIdps()==castOther.getIdps())
 && (this.getIdseas()==castOther.getIdseas());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdps();
         result = 37 * result + this.getIdseas();
         return result;
   }   


}


