package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1



/**
 * Possederps generated by hbm2java
 */
public class Possederps  implements java.io.Serializable {


     private PossederpsId id;
     private Programmestandard programmestandard;
     private Seancestandard seancestandard;
     private Integer ordredefaut;

    public Possederps() {
    }

	
    public Possederps(PossederpsId id, Programmestandard programmestandard, Seancestandard seancestandard) {
        this.id = id;
        this.programmestandard = programmestandard;
        this.seancestandard = seancestandard;
    }
    public Possederps(PossederpsId id, Programmestandard programmestandard, Seancestandard seancestandard, Integer ordredefaut) {
       this.id = id;
       this.programmestandard = programmestandard;
       this.seancestandard = seancestandard;
       this.ordredefaut = ordredefaut;
    }
   
    public PossederpsId getId() {
        return this.id;
    }
    
    public void setId(PossederpsId id) {
        this.id = id;
    }
    public Programmestandard getProgrammestandard() {
        return this.programmestandard;
    }
    
    public void setProgrammestandard(Programmestandard programmestandard) {
        this.programmestandard = programmestandard;
    }
    public Seancestandard getSeancestandard() {
        return this.seancestandard;
    }
    
    public void setSeancestandard(Seancestandard seancestandard) {
        this.seancestandard = seancestandard;
    }
    public Integer getOrdredefaut() {
        return this.ordredefaut;
    }
    
    public void setOrdredefaut(Integer ordredefaut) {
        this.ordredefaut = ordredefaut;
    }




}


