package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Programmestandard generated by hbm2java
 */
public class Programmestandard  implements java.io.Serializable {


     private Integer idps;
     private String libps;
     private String descripps;
     private Integer dureeps;
     private Set possederpses = new HashSet(0);
     private Set objectifs = new HashSet(0);

    public Programmestandard() {
    }

    public Programmestandard(String libps, String descripps, Integer dureeps, Set possederpses, Set objectifs) {
       this.libps = libps;
       this.descripps = descripps;
       this.dureeps = dureeps;
       this.possederpses = possederpses;
       this.objectifs = objectifs;
    }
   
    public Integer getIdps() {
        return this.idps;
    }
    
    public void setIdps(Integer idps) {
        this.idps = idps;
    }
    public String getLibps() {
        return this.libps;
    }
    
    public void setLibps(String libps) {
        this.libps = libps;
    }
    public String getDescripps() {
        return this.descripps;
    }
    
    public void setDescripps(String descripps) {
        this.descripps = descripps;
    }
    public Integer getDureeps() {
        return this.dureeps;
    }
    
    public void setDureeps(Integer dureeps) {
        this.dureeps = dureeps;
    }
    public Set getPossederpses() {
        return this.possederpses;
    }
    
    public void setPossederpses(Set possederpses) {
        this.possederpses = possederpses;
    }
    public Set getObjectifs() {
        return this.objectifs;
    }
    
    public void setObjectifs(Set objectifs) {
        this.objectifs = objectifs;
    }




}


