package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Programmeperso generated by hbm2java
 */
public class Programmeperso  implements java.io.Serializable {


     private Integer idpp;
     private Client client;
     private String libpp;
     private String descrippp;
     private Integer dureepp;
     private String etatpp;
     private Date dateaffecte;
     private Set seancepersos = new HashSet(0);
     private Set objectifs = new HashSet(0);

    public Programmeperso() {
    }

	
    public Programmeperso(Client client) {
        this.client = client;
    }
    public Programmeperso(Client client, String libpp, String descrippp, Integer dureepp, String etatpp, Date dateaffecte, Set seancepersos, Set objectifs) {
       this.client = client;
       this.libpp = libpp;
       this.descrippp = descrippp;
       this.dureepp = dureepp;
       this.etatpp = etatpp;
       this.dateaffecte = dateaffecte;
       this.seancepersos = seancepersos;
       this.objectifs = objectifs;
    }
   
    public Integer getIdpp() {
        return this.idpp;
    }
    
    public void setIdpp(Integer idpp) {
        this.idpp = idpp;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getLibpp() {
        return this.libpp;
    }
    
    public void setLibpp(String libpp) {
        this.libpp = libpp;
    }
    public String getDescrippp() {
        return this.descrippp;
    }
    
    public void setDescrippp(String descrippp) {
        this.descrippp = descrippp;
    }
    public Integer getDureepp() {
        return this.dureepp;
    }
    
    public void setDureepp(Integer dureepp) {
        this.dureepp = dureepp;
    }
    public String getEtatpp() {
        return this.etatpp;
    }
    
    public void setEtatpp(String etatpp) {
        this.etatpp = etatpp;
    }
    public Date getDateaffecte() {
        return this.dateaffecte;
    }
    
    public void setDateaffecte(Date dateaffecte) {
        this.dateaffecte = dateaffecte;
    }
    public Set getSeancepersos() {
        return this.seancepersos;
    }
    
    public void setSeancepersos(Set seancepersos) {
        this.seancepersos = seancepersos;
    }
    public Set getObjectifs() {
        return this.objectifs;
    }
    
    public void setObjectifs(Set objectifs) {
        this.objectifs = objectifs;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 71 * hash + Objects.hashCode(this.idpp);
        hash = 71 * hash + Objects.hashCode(this.libpp);
        hash = 71 * hash + Objects.hashCode(this.descrippp);
        hash = 71 * hash + Objects.hashCode(this.dureepp);
        hash = 71 * hash + Objects.hashCode(this.etatpp);
        hash = 71 * hash + Objects.hashCode(this.dateaffecte);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Programmeperso other = (Programmeperso) obj;
        if (!Objects.equals(this.libpp, other.libpp)) {
            return false;
        }
        if (!Objects.equals(this.descrippp, other.descrippp)) {
            return false;
        }
        if (!Objects.equals(this.etatpp, other.etatpp)) {
            return false;
        }
        if (!Objects.equals(this.idpp, other.idpp)) {
            return false;
        }
        if (!Objects.equals(this.dureepp, other.dureepp)) {
            return false;
        }
        if (!Objects.equals(this.dateaffecte, other.dateaffecte)) {
            return false;
        }
        return true;
    }




}


