package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seancestandard generated by hbm2java
 */
public class Seancestandard  implements java.io.Serializable {


     private Integer idseas;
     private String libseas;
     private String descripseas;
     private String typeseas;
     private Set exercisestandards = new HashSet(0);
     private Set possederpses = new HashSet(0);

    public Seancestandard() {
    }

    public Seancestandard(String libseas, String descripseas, String typeseas, Set exercisestandards, Set possederpses) {
       this.libseas = libseas;
       this.descripseas = descripseas;
       this.typeseas = typeseas;
       this.exercisestandards = exercisestandards;
       this.possederpses = possederpses;
    }
   
    public Integer getIdseas() {
        return this.idseas;
    }
    
    public void setIdseas(Integer idseas) {
        this.idseas = idseas;
    }
    public String getLibseas() {
        return this.libseas;
    }
    
    public void setLibseas(String libseas) {
        this.libseas = libseas;
    }
    public String getDescripseas() {
        return this.descripseas;
    }
    
    public void setDescripseas(String descripseas) {
        this.descripseas = descripseas;
    }
    public String getTypeseas() {
        return this.typeseas;
    }
    
    public void setTypeseas(String typeseas) {
        this.typeseas = typeseas;
    }
    public Set getExercisestandards() {
        return this.exercisestandards;
    }
    
    public void setExercisestandards(Set exercisestandards) {
        this.exercisestandards = exercisestandards;
    }
    public Set getPossederpses() {
        return this.possederpses;
    }
    
    public void setPossederpses(Set possederpses) {
        this.possederpses = possederpses;
    }




}


