package Bd;
// Generated 26 mars 2019 16:30:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Seanceperso generated by hbm2java
 */
public class Seanceperso  implements java.io.Serializable {


     private Integer idsea;
     private Programmeperso programmeperso;
     private String libsea;
     private String descrisea;
     private String typesea;
     private Date datesea;
     private Integer ordresea;
     private Double bras;
     private Double poitrine;
     private Double taille;
     private Double hanches;
     private Double cuisses;
     private Set exercisepersos = new HashSet(0);

    public Seanceperso() {
    }

	
    public Seanceperso(Programmeperso programmeperso) {
        this.programmeperso = programmeperso;
    }
    public Seanceperso(Programmeperso programmeperso, String libsea, String descrisea, String typesea, Date datesea, Integer ordresea, Double bras, Double poitrine, Double taille, Double hanches, Double cuisses, Set exercisepersos) {
       this.programmeperso = programmeperso;
       this.libsea = libsea;
       this.descrisea = descrisea;
       this.typesea = typesea;
       this.datesea = datesea;
       this.ordresea = ordresea;
       this.bras = bras;
       this.poitrine = poitrine;
       this.taille = taille;
       this.hanches = hanches;
       this.cuisses = cuisses;
       this.exercisepersos = exercisepersos;
    }
   
    public Integer getIdsea() {
        return this.idsea;
    }
    
    public void setIdsea(Integer idsea) {
        this.idsea = idsea;
    }
    public Programmeperso getProgrammeperso() {
        return this.programmeperso;
    }
    
    public void setProgrammeperso(Programmeperso programmeperso) {
        this.programmeperso = programmeperso;
    }
    public String getLibsea() {
        return this.libsea;
    }
    
    public void setLibsea(String libsea) {
        this.libsea = libsea;
    }
    public String getDescrisea() {
        return this.descrisea;
    }
    
    public void setDescrisea(String descrisea) {
        this.descrisea = descrisea;
    }
    public String getTypesea() {
        return this.typesea;
    }
    
    public void setTypesea(String typesea) {
        this.typesea = typesea;
    }
    public Date getDatesea() {
        return this.datesea;
    }
    
    public void setDatesea(Date datesea) {
        this.datesea = datesea;
    }
    public Integer getOrdresea() {
        return this.ordresea;
    }
    
    public void setOrdresea(Integer ordresea) {
        this.ordresea = ordresea;
    }
    public Double getBras() {
        return this.bras;
    }
    
    public void setBras(Double bras) {
        this.bras = bras;
    }
    public Double getPoitrine() {
        return this.poitrine;
    }
    
    public void setPoitrine(Double poitrine) {
        this.poitrine = poitrine;
    }
    public Double getTaille() {
        return this.taille;
    }
    
    public void setTaille(Double taille) {
        this.taille = taille;
    }
    public Double getHanches() {
        return this.hanches;
    }
    
    public void setHanches(Double hanches) {
        this.hanches = hanches;
    }
    public Double getCuisses() {
        return this.cuisses;
    }
    
    public void setCuisses(Double cuisses) {
        this.cuisses = cuisses;
    }
    public Set getExercisepersos() {
        return this.exercisepersos;
    }
    
    public void setExercisepersos(Set exercisepersos) {
        this.exercisepersos = exercisepersos;
    }




}


